#!/bin/bash
#
# Google Music Manager Wrapper
# Copyright (C) 2017 James T. Lee
#
# The google-musicmanager process daemonizes itself which causes the Docker
# container to stop.  This wrapper waits for the daemon to stop, and takes care
# to pass a couple of exit signals to it.
#

/usr/bin/google-musicmanager "$@"
pid="$(pgrep -f /usr/bin/google-musicmanager)"
trap "kill -INT '${pid}'" INT
trap "kill -TERM '${pid}'" TERM
while [[ -d "/proc/${pid}" ]]; do sleep 1; done
